CREATE SCHEMA SCHEMA_PECERA;

CREATE SEQUENCE SCHEMA_PECERA.SQ_PECERAS MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1;

CREATE TABLE SCHEMA_PECERA.PECERAS (
	ID NUMBER(11) NOT NULL,
	VALUE_DATA VARCHAR2(255 BYTE) NULL,
	VALUE_OBJECT_VALUE VARCHAR2(255 BYTE) NULL,
	ELIMINADO NUMBER(1,0) NOT NULL
);

ALTER TABLE SCHEMA_PECERA.PECERAS ADD (
	CONSTRAINT CN_PECERAS_PK PRIMARY KEY (ID)
);