custom:
  topic:
     pecera:
      posted: PostedPeceraTopic
      modified: ModifiedPeceraTopic
      deleted: DeletedPeceraTopic
      input-event: InputEventPeceraTopic

spring:
  kafka:
    url: localhost:9095
    consumer:
      auto-offset-reset: earliest
      group-id: pecera-group-id
      group-id-test: test-pecera-group-id
    timeout: 6000

  datasource:
    url: jdbc:h2:mem:PECERA_DB;DB_CLOSE_DELAY=-1;MODE=ORACLE
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    
logging:
  level:
    root: INFO
    kafka: OFF
    org.apache: ERROR
    org.springframework: ERROR