


spring:
  application.name: MongoTest
  data:
    mongodb:
      host: localhost
      port: 27018
      database: IEM_tests
      #username: admin
      #password: admin

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 8.0.0