
//THE BELOW WOULD BE LIKE WHAT WE CREARED IN THE USER CLASS

CREATE TABLE IF NOT EXISTS USERS (
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL, 
	EMAIL VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS ROLES (
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL, 
	DESCRIPTION VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS PERMISSIONS (
	ID_ROLE BIGINT PRIMARY KEY,
	PERMISSION VARCHAR(255) NOT NULL
)

//THE ABOVE TWO ATTRIBUTES FORM PART OF THE PERMISSIONSID CLASS WHICH IS THE ONE ATTIRBUTE ASSIGNED TO THE PERMISSIONS CLASS.
//THE BELOW JOINS THE TWO ATTRIBUTES TO FORM THE ONE MASTER ID (ATTRIBUTE OF PERMISSIONS) WHICH IS A COMBINATION OF ROLE ID AND PERMISSION ID

ALTER TABLE PERMISSIONS
  ADD CONSTRAINT PERMISSIONS_ID UNIQUE (ID_ROLE,PERMISSION)